[package]
name = "ownership"
version = "0.1.0"
authors = ["dapplion <35266934+dapplion@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
